import { Inter } from 'next/font/google';

import { CssVarsProvider } from '@/libs/mui/CssVarsProvider';
import { theme } from '@/libs/mui/theme';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssVarsProvider theme={theme}>{children}</CssVarsProvider>
      </body>
    </html>
  );
}
