version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: inspicto-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword